# BukkitTelnet v4.2 Configuration File
# Made by TFM-Developers and Edited by reuben4545.

# Address to listen on, leave blank for all
address: ''

# Port to bind to:
port: 9475

# Main connection password, must be defined
password: 'bukkittelnet'

# List of admins / IPs that don't have to use the password
admins:
  reuben4545:
    - 86.157.32.3
