name: BukkitTelnetv4.2
main: me.StevenLawson.BukkitTelnet.BukkitTelnet
version: 4.2
description: Telnet console access plugin made by TFM-Developers and edited by reuben4545.
authors: [bekvon, Madgeek1450, DarthSalamon, reuben4545]
